package dam.biblioteca;

public enum Categoria {
	GENERAL, FILOSOFIA_Y_PSICOLOGIA, RELIGION_Y_TEOLOGIA, CIENCIAS_SOCIALES, LENGUAS, 
	CIENCIAS_BASICAS, TECNOLOGIA_Y_CIENCIAS_APLICADAS, ARTES_Y_RECREACION, HISTORIA_Y_GEOGRAFIA
}
